name: Build & Test

on:
  push:
    branches: [master, develop, "feat/*"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "example/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "example/**"

jobs:
  e2e-test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: "Install dependencies"
        run: yarn install --frozen-lockfile
      - name: "Run tests"
        run: yarn run test

